# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summoner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='region',
            field=models.CharField(choices=[('BR', 'Brazil'), ('EUNE', 'EU Nordic & East'), ('EUW', 'EU West'), ('JP', 'Japan'), ('KR', 'Korea'), ('LAN', 'Latin America North'), ('LAS', 'Latin America South'), ('NA', 'North America'), ('OCE', 'Oceania'), ('RU', 'Russia'), ('TR', 'Turkey')], default='EUW', max_length=4, verbose_name='region'),
            preserve_default=False,
        ),
    ]
