# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-21 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=80, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('order', models.IntegerField(verbose_name='order')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
