# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-21 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20170215_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='notes',
            field=models.TextField(help_text='Add notes for this match. What went well? How can you improve?', null=True),
        ),
    ]
