# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20170221_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='assists'),
        ),
        migrations.AddField(
            model_name='match',
            name='champion_id',
            field=models.IntegerField(null=True, verbose_name='champion'),
        ),
        migrations.AddField(
            model_name='match',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='match',
            name='deaths',
            field=models.IntegerField(default=0, verbose_name='deaths'),
        ),
        migrations.AddField(
            model_name='match',
            name='kills',
            field=models.IntegerField(default=0, verbose_name='kills'),
        ),
        migrations.AddField(
            model_name='match',
            name='minions',
            field=models.IntegerField(default=0, verbose_name='cs'),
        ),
        migrations.AddField(
            model_name='match',
            name='win',
            field=models.BooleanField(default=False, verbose_name='win'),
        ),
    ]
