# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20170222_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='champion_name',
            field=models.IntegerField(null=True, verbose_name='champion name'),
        ),
        migrations.AlterField(
            model_name='match',
            name='champion_id',
            field=models.IntegerField(null=True, verbose_name='champion id'),
        ),
    ]
