# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20170301_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='champion_name',
            field=models.CharField(max_length=50, null=True, verbose_name='champion name'),
        ),
    ]
