# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-03 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_auto_20170301_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='game_type',
            field=models.CharField(max_length=50, null=True, verbose_name='game type'),
        ),
    ]
